import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import PlayingController from "./_components/PlayingController/PlayingController";
import "@ant-design/v5-patch-for-react-19";
import { CounterStoreProvider } from "./_providers/counter-store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <div className="flex h-screen w-full">
            <Navbar />

            <div className="flex-[5] bg-bgColor px-16 py-8 text-textColor">
              <CounterStoreProvider>{children}</CounterStoreProvider>
            </div>

            <div className="fixed bottom-0 left-0 right-0 z-50">
              <PlayingController />
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
